
platform :ios, '8.0'
pod "AFNetworking", '~> 2.5.4'
pod 'Masonry', '~> 0.6.1'
pod 'MJExtension', '~> 2.1.1'
pod 'MJRefresh', '~> 2.4.12'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'SDWebImage', '~> 3.7.3'
pod 'Reachability', '~> 3.2'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'ZBarSDK', '~> 1.3.1'
pod 'libqrencode', '~> 3.4.2'
pod 'BabyBluetooth','~> 0.4.0'
pod 'MKFoundationKit/NSArray', '~> 1.2.2'
